### ISSUE TITLE
Compatiblité avec IE12

### ISSUE THREAD

**Issue by charles-plessy** [woleet/btcproof.info#1]
Votre commit numéro 9b9db1a8329ad1db505d2b0a386c4b841e599867 nous informe que « _tu es en trian de me dire que btcproof n'a jamais marché sur IE12?_ ».  Peut-être y-a-t-il une manière plus adroite d'en informer nos amis anglophones...

Meilleurs vœux,

**Comment by vincentbarat** [comment]
Bonjour et merci pour votre "découverte" :-) Je ne sais pas comment vous avez fait pour voir ça passer...
C'est un message Slack qui c'est retrouvé au mauvais endroit.

C'est corrigé !

Cordialement,
